const data = [
    {
        name: "Meer over ons bedrijf",
        phrase: [
            "contact",
            "phone",
            "call",
            "telefoon",
            "tel",
            "straat",
            "adres",
            "map",
            "kaart",
            "route",
            "openingstijden",
            "over ons",
            "stad",
            "gegevens",
            "",
        ],
        path: "/contact",
    },
    {
        name: "IT Context Diensten",
        phrase: [
            "dienst",
            "diensten",
            "service",
            "online marketing",
            "web",
            "design",
            "ontwerp",
            "ontwikkelen",
            "ontwikkel",
            "website",
            "app",
            "hosting",
            "e-mail",
            "social",
            "media",
            "ads",
            "advertenties",
            "content",
            "management",
            "systeem",
            "cms",
            "server",
        ],
        path: "/diensten",
    },
    {
        name: "Lees meer over Online Marketing",
        phrase: ["online", "marketing", "ads", "advertentie"],
        path: "/diensten/online-marketing",
    },
    {
        name: "IT Context Prijzen",
        phrase: ["prijzen", "prijs", "geld"],
        path: "/prijzen",
    },
    {
        name: "IT Context Projecten",
        phrase: [
            "project",
            "projecten",
            "voorbeeld",
            "werk",
            "ontwerp",
            "design",
            "website",
        ],
        path: "/projecten",
    },
    {
        name: "IT Context Algemene Voorwaarden",
        phrase: [
            "online marketing",
            "web",
            "design",
            "ontwerp",
            "ontwikkelen",
            "ontwikkel",
            "website",
            "app",
            "hosting",
            "e-mail",
            "social",
            "media",
            "ads",
            "advertenties",
            "content",
            "management",
            "systeem",
            "cms",
            "server",
        ],
        path: "/voorwaarden",
    },
    {
        name: "IT Context Privacybeleid",
        phrase: [
            "privacy",
            "cookies",
            "legal",
            "recht",
            "voorwaarden",
            "policy",
        ],
        path: "/cookies",
    },
];
export default function search(phrase, setFunction) {
    const x = phrase.toLowerCase();
    const results = data.filter((each) => {
        return each.phrase.find((w) => w.includes(x));
    });
    console.log(results);
    const payload = results.map((r) => ({ name: r.name, path: r.path }));
    return setFunction(payload);
}
